del *.~*
del *.tpu
del Visual*.dat
del xy*.dat
del *.dcu
del *.ddp
del history.dat
del Ions.dat
del LFP.dat
del PinWheels.dat
del spectr.dat
del WriteFromNode.dat
del WriteFromNode2.dat
del VeViVrAP.dat
del SigmE(V).dat
del SigmI(V).dat
del Representatives_U_nu(t).dat
del RF*.dat
del Ring(t,x).dat
del PWCenters.dat
del InnerCond.dat
del SynCond.dat
del Screen.jpg
del _MyComponents\*.dcu
del _ObjectsOfNeuron\*.dcu
del _LGN\*.dcu
del Visualizator\*.dcu
