unit ReadWriteSettings;

interface
uses Unit3,Unit4,Unit15,Unit24,Unit25,Unit26,Unit30,
     LGN_Unit1,LGN_Unit15,
     Init,MathMyO,Correspond,gsynC,
     Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs;

procedure SaveSettings(FName :string);
procedure LoadSettings(FName :string);

implementation
uses Unit1,Unit5,Unit11,Unit31;

procedure SaveSettings(FName :string);
var aaa :text;
    k,ib :integer;
begin
  assign(aaa,FName); rewrite(aaa);
  {****************************************************************************}
  { Form4 }
  writeln(aaa,'Form4');
  writeln(aaa,Form4.DDSpinEdit1.Value:9:4,' :DDSpinEdit1');
  writeln(aaa,Form4.DDSpinEdit2.Value:9:4,' :DDSpinEdit2');
  writeln(aaa,Form4.DDSpinEdit3.Value:9:4,' :DDSpinEdit3');
  writeln(aaa,Form4.DDSpinEdit4.Value:9:4,' :DDSpinEdit4');
  writeln(aaa,Form4.DDSpinEdit5.Value:9:4,' :DDSpinEdit5');
  writeln(aaa,Form4.DDSpinEdit6.Value:9:4,' :DDSpinEdit6');
  writeln(aaa,Form4.DDSpinEdit7.Value:9:4,' :DDSpinEdit7');
  writeln(aaa,Form4.DDSpinEdit8.Value:9:4,' :DDSpinEdit8');
  writeln(aaa,Form4.DDSpinEdit9.Value:9:4,' :DDSpinEdit9');
  writeln(aaa,Form4.DDSpinEdit10.Value:9:4,' :DDSpinEdit10');
  writeln(aaa,Form4.DDSpinEdit11.Value:9:4,' :DDSpinEdit11');
  writeln(aaa,Form4.DDSpinEdit12.Value:9:4,' :DDSpinEdit12');
  writeln(aaa,Form4.DDSpinEdit13.Value:9:4,' :DDSpinEdit13');
  writeln(aaa,Form4.DDSpinEdit14.Value:9:4,' :DDSpinEdit14');
  writeln(aaa,Form4.DDSpinEdit15.Value:9:4,' :DDSpinEdit15');
  writeln(aaa,Form4.DDSpinEdit16.Value:9:4,' :DDSpinEdit16');
  writeln(aaa,Form4.DDSpinEdit17.Value:9:4,' :DDSpinEdit17');
  writeln(aaa,Form4.DDSpinEdit18.Value:9:4,' :DDSpinEdit18');
  writeln(aaa,Form4.DDSpinEdit19.Value:9:4,' :DDSpinEdit19');
  writeln(aaa,Form4.DDSpinEdit20.Value:9:4,' :DDSpinEdit20');
  writeln(aaa,Form4.DDSpinEdit21.Value:9:4,' :DDSpinEdit21');
  writeln(aaa,Form4.DDSpinEdit22.Value:9:4,' :DDSpinEdit22');
  writeln(aaa,Form4.DDSpinEdit23.Value:9:4,' :DDSpinEdit23');
  writeln(aaa,Form4.DDSpinEdit24.Value:9:4,' :DDSpinEdit24');
  writeln(aaa,Form4.DDSpinEdit25.Value:9:4,' :DDSpinEdit25');
  writeln(aaa,Form4.DDSpinEdit26.Value:9:4,' :DDSpinEdit26');
  writeln(aaa,Form4.DDSpinEdit27.Value:9:4,' :DDSpinEdit27');
  writeln(aaa,Form4.DDSpinEdit28.Value:9:4,' :DDSpinEdit28');
  writeln(aaa,Form4.DDSpinEdit29.Value:9:4,' :DDSpinEdit29');
  writeln(aaa,Form4.DDSpinEdit30.Value:9:4,' :DDSpinEdit30');
  writeln(aaa,Form4.DDSpinEdit31.Value:9:4,' :DDSpinEdit31');
  writeln(aaa,Form4.DDSpinEdit32.Value:9:4,' :DDSpinEdit32');
  writeln(aaa,Form4.DDSpinEdit33.Value:9:4,' :DDSpinEdit33');
  writeln(aaa,Form4.DDSpinEdit34.Value:9:4,' :DDSpinEdit34');
  writeln(aaa,Form4.DDSpinEdit35.Value:9:4,' :DDSpinEdit35');
  writeln(aaa,Form4.DDSpinEdit36.Value:9:4,' :DDSpinEdit36');
  writeln(aaa,Form4.DDSpinEdit37.Value:9:4,' :DDSpinEdit37');
  writeln(aaa,Form4.DDSpinEdit38.Value:9:4,' :DDSpinEdit38');
  writeln(aaa,Form4.DDSpinEdit39.Value:9:4,' :DDSpinEdit39');
  writeln(aaa,Form4.DDSpinEdit40.Value:9:4,' :DDSpinEdit40');
  writeln(aaa,Form4.DDSpinEdit41.Value:9:4,' :DDSpinEdit41');
  writeln(aaa,Form4.DDSpinEdit42.Value:9:4,' :DDSpinEdit42');
  writeln(aaa,Form4.DDSpinEdit43.Value:9:4,' :DDSpinEdit43');
  writeln(aaa,Form4.DDSpinEdit44.Value:9:4,' :DDSpinEdit44');
  writeln(aaa,Form4.DDSpinEdit45.Value:9:4,' :DDSpinEdit45');
  writeln(aaa,Form4.DDSpinEdit46.Value:9:4,' :DDSpinEdit46');
  writeln(aaa,Form4.DDSpinEdit47.Value:9:4,' :DDSpinEdit47');
  writeln(aaa,Form4.DDSpinEdit48.Value:9:4,' :DDSpinEdit48');
  writeln(aaa,Form4.DDSpinEdit49.Value:9:4,' :DDSpinEdit49');
  writeln(aaa,Form4.DDSpinEdit50.Value:9:4,' :DDSpinEdit50');
  writeln(aaa,Form4.DDSpinEdit51.Value:9:4,' :DDSpinEdit51');
  writeln(aaa,Form4.DDSpinEdit52.Value:9:4,' :DDSpinEdit52');
  writeln(aaa,Form4.DDSpinEdit53.Value:9:4,' :DDSpinEdit53');
  writeln(aaa,Form4.DDSpinEdit54.Value:9:4,' :DDSpinEdit54');
  writeln(aaa,Form4.DDSpinEdit55.Value:9:4,' :DDSpinEdit55');
  writeln(aaa,Form4.DDSpinEdit56.Value:9:4,' :DDSpinEdit56');
  writeln(aaa,Form4.DDSpinEdit57.Value:9:4,' :DDSpinEdit57');
  writeln(aaa,Form4.DDSpinEdit58.Value:9:4,' :DDSpinEdit58');
  writeln(aaa,Form4.DDSpinEdit59.Value:9:4,' :DDSpinEdit59');
  writeln(aaa,Form4.DDSpinEdit60.Value:9:4,' :DDSpinEdit60');
  writeln(aaa,Form4.DDSpinEdit61.Value:9:4,' :DDSpinEdit61');
  writeln(aaa,Form4.DDSpinEdit62.Value:9:4,' :DDSpinEdit62');
  writeln(aaa,Form4.DDSpinEdit63.Value:9:4,' :DDSpinEdit63');
  writeln(aaa,Form4.DDSpinEdit64.Value:9:4,' :DDSpinEdit64');
  writeln(aaa,Form4.DDSpinEdit65.Value:9:4,' :DDSpinEdit65');
  writeln(aaa,Form4.DDSpinEdit66.Value:9:4,' :DDSpinEdit66');
  writeln(aaa,Form4.DDSpinEdit67.Value:9:4,' :DDSpinEdit67');
  writeln(aaa,Form4.DDSpinEdit68.Value:9:4,' :DDSpinEdit68');
  writeln(aaa,Form4.DDSpinEdit69.Value:9:4,' :DDSpinEdit69');
  writeln(aaa,Form4.DDSpinEdit70.Value:9:4,' :DDSpinEdit70');
  writeln(aaa,Form4.DDSpinEdit71.Value:9:4,' :DDSpinEdit71');
  writeln(aaa); //,Form4.DDSpinEdit72.Value:9:4,' :DDSpinEdit72');
  writeln(aaa,Form4.DDSpinEdit73.Value:9:4,' :DDSpinEdit73');
  writeln(aaa,Form4.DDSpinEdit74.Value:9:4,' :DDSpinEdit74');
  writeln(aaa,Form4.DDSpinEdit75.Value:9:4,' :DDSpinEdit75');
  writeln(aaa,Form4.DDSpinEdit76.Value:9:4,' :DDSpinEdit76');
  writeln(aaa,Form4.DDSpinEdit80.Value:9:4,' :DDSpinEdit80');
  writeln(aaa,Form4.DDSpinEdit81.Value:9:4,' :DDSpinEdit81');
  writeln(aaa,Form4.DDSpinEdit83.Value:9:4,' :DDSpinEdit83');
  writeln(aaa,Form4.DDSpinEdit84.Value:9:4,' :DDSpinEdit84');
  writeln(aaa,Form4.DDSpinEdit85.Value:9:4,' :DDSpinEdit85');
  writeln(aaa,Form4.DDSpinEdit86.Value:9:4,' :DDSpinEdit86');
  writeln(aaa,Form4.DDSpinEdit87.Value:9:4,' :DDSpinEdit87');
  writeln(aaa,Form4.DDSpinEdit88.Value:9:4,' :DDSpinEdit88');
  writeln(aaa,Form4.DDSpinEdit89.Value:9:4,' :DDSpinEdit89');
  writeln(aaa,Form4.DDSpinEdit90.Value:9:4,' :DDSpinEdit90');
  writeln(aaa,Form4.DDSpinEdit91.Value:9:4,' :DDSpinEdit91');
  writeln(aaa,Form4.DDSpinEdit92.Value:9:4,' :DDSpinEdit92');
  writeln(aaa,Form4.DDSpinEdit93.Value:9:4,' :DDSpinEdit93');
  writeln(aaa,Form4.DDSpinEdit94.Value:9:4,' :DDSpinEdit94');
  writeln(aaa,Form4.DDSpinEdit96.Value:9:4,' :DDSpinEdit96');
  writeln(aaa,Form4.DDSpinEdit97.Value:9:4,' :DDSpinEdit97');
  writeln(aaa,Form4.DDSpinEdit98.Value:9:4,' :DDSpinEdit98');
  writeln(aaa,Form4.DDSpinEdit106.Value:9:4,' :DDSpinEdit106');
  writeln(aaa,Form4.DDSpinEdit107.Value:9:4,' :DDSpinEdit107');
  writeln(aaa,Form4.DDSpinEdit108.Value:9:4,' :DDSpinEdit108');
  writeln(aaa,Form4.DDSpinEdit109.Value:9:4,' :DDSpinEdit109');
  writeln(aaa,Form4.DDSpinEdit110.Value:9:4,' :DDSpinEdit110');
  writeln(aaa,Form4.DDSpinEdit111.Value:9:4,' :DDSpinEdit111');
  writeln(aaa,Form4.DDSpinEdit112.Value:9:4,' :DDSpinEdit112');
  writeln(aaa,Form4.DDSpinEdit113.Value:9:4,' :DDSpinEdit113');
  writeln(aaa,Form4.DDSpinEdit114.Value:9:4,' :DDSpinEdit114');
  writeln(aaa,Form4.DDSpinEdit115.Value:9:4,' :DDSpinEdit115');
  writeln(aaa,Form4.DDSpinEdit116.Value:9:4,' :DDSpinEdit116');
  { Form4.gsynC1 }
  for k:=1 to MaxNSyn do begin
      writeln(aaa,Form4.gsynC1.DDSpinEditA[k].Value:9:4,' :DDSpinEditA[',k:3,']');
  end;
  writeln(aaa,Form4.ComboBox1.ItemIndex:3,' ComboBox1');
  writeln(aaa,Form4.ComboBox2.ItemIndex:3,' ComboBox2');
  writeln(aaa,Form4.ComboBox3.ItemIndex:3,' ComboBox3');
  writeln(aaa,Form4.ComboBox4.ItemIndex:3,' ComboBox4');
  writeln(aaa,Form4.ComboBox5.ItemIndex:3,' ComboBox5');
  writeln(aaa,Form4.ComboBox6.ItemIndex:3,' ComboBox6');
  writeln(aaa,IfTrue(Form4.CheckBox1.Checked):3,' CheckBox1');
  writeln(aaa,IfTrue(Form4.CheckBox2.Checked):3,' CheckBox2');
  writeln(aaa,IfTrue(Form4.CheckBox3.Checked):3,' CheckBox3');
  writeln(aaa,IfTrue(Form4.CheckBox4.Checked):3,' CheckBox4');
  writeln(aaa,IfTrue(Form4.CheckBox5.Checked):3,' CheckBox5');
  writeln(aaa,IfTrue(Form4.CheckBox6.Checked):3,' CheckBox6');
  writeln(aaa,'void');
  writeln(aaa,IfTrue(Form4.CheckBox8.Checked):3,' CheckBox8');
  writeln(aaa,IfTrue(Form4.CheckBox9.Checked):3,' CheckBox9');
  writeln(aaa,IfTrue(Form4.CheckBox10.Checked):3,' CheckBox10');
  writeln(aaa,IfTrue(Form4.CheckBox11.Checked):3,' CheckBox11');
  writeln(aaa,IfTrue(Form4.CheckBox12.Checked):3,' CheckBox12');
  writeln(aaa,IfTrue(Form4.CheckBox14.Checked):3,' CheckBox14');
  writeln(aaa,IfTrue(Form4.CheckBox15.Checked):3,' CheckBox15');
  writeln(aaa,IfTrue(Form4.CheckBox16.Checked):3,' CheckBox16');
  writeln(aaa,Form4.ComboBox7.ItemIndex:3,' ComboBox7');
  writeln(aaa,IfTrue(Form4.CheckBox18.Checked):3,' CheckBox18');
  writeln(aaa,IfTrue(Form4.CheckBox19.Checked):3,' CheckBox19');
  writeln(aaa,IfTrue(Form4.CheckBox20.Checked):3,' CheckBox20');
  {****************************************************************************}
  { Form3 }
  writeln(aaa,'Form3');
  writeln(aaa,Form3.DDSpinEdit1.Value:9:4,' :DDSpinEdit1');
  writeln(aaa,Form3.DDSpinEdit2.Value:9:4,' :DDSpinEdit2');
  writeln(aaa,Form3.DDSpinEdit3.Value:9:4,' :DDSpinEdit3');
  writeln(aaa,Form3.DDSpinEdit4.Value:9:4,' :DDSpinEdit4');
  writeln(aaa,Form3.DDSpinEdit5.Value:9:4,' :DDSpinEdit5');
  writeln(aaa,Form3.DDSpinEdit6.Value:9:4,' :DDSpinEdit6');
  writeln(aaa,Form3.DDSpinEdit7.Value:9:4,' :DDSpinEdit7');
  writeln(aaa,Form3.DDSpinEdit8.Value:9:4,' :DDSpinEdit8');
  writeln(aaa,Form3.DDSpinEdit9.Value:9:4,' :DDSpinEdit9');
  writeln(aaa,Form3.DDSpinEdit10.Value:9:4,' :DDSpinEdit10');
  writeln(aaa,Form3.DDSpinEdit11.Value:9:4,' :DDSpinEdit11');
  writeln(aaa,Form3.DDSpinEdit12.Value:9:4,' :DDSpinEdit12');
  writeln(aaa,Form3.DDSpinEdit13.Value:9:4,' :DDSpinEdit13');
  writeln(aaa,Form3.DDSpinEdit14.Value:9:4,' :DDSpinEdit14');
  writeln(aaa,Form3.DDSpinEdit15.Value:9:4,' :DDSpinEdit15');
  writeln(aaa,Form3.DDSpinEdit16.Value:9:4,' :DDSpinEdit16');
  writeln(aaa,Form3.DDSpinEdit17.Value:9:4,' :DDSpinEdit17');
  writeln(aaa,Form3.DDSpinEdit18.Value:9:4,' :DDSpinEdit18');
  writeln(aaa,Form3.DDSpinEdit19.Value:9:4,' :DDSpinEdit19');
  writeln(aaa,Form3.DDSpinEdit20.Value:9:4,' :DDSpinEdit20');
  writeln(aaa,Form3.DDSpinEdit21.Value:9:4,' :DDSpinEdit21');
  writeln(aaa,Form3.DDSpinEdit24.Value:9:4,' :DDSpinEdit24');
  writeln(aaa,Form3.DDSpinEdit25.Value:9:4,' :DDSpinEdit25');
  writeln(aaa,Form3.DDSpinEdit26.Value:9:4,' :DDSpinEdit26');
  writeln(aaa,Form3.DDSpinEdit27.Value:9:4,' :DDSpinEdit27');
  writeln(aaa,Form3.ComboBox1.ItemIndex:3,' ComboBox1');
  writeln(aaa,Form3.ComboBox2.ItemIndex:3,' ComboBox2');
  writeln(aaa,Form3.ComboBox3.ItemIndex:3,' ComboBox3');
  writeln(aaa,IfTrue(Form3.CheckBox1.Checked):3,' CheckBox1');
  writeln(aaa,IfTrue(Form3.CheckBox2.Checked):3,' CheckBox2');
  writeln(aaa,IfTrue(Form3.CheckBox3.Checked):3,' CheckBox3');
  writeln(aaa,IfTrue(Form3.CheckBox4.Checked):3,' CheckBox4');
  writeln(aaa,IfTrue(Form3.CheckBox5.Checked):3,' CheckBox5');
  writeln(aaa,IfTrue(Form3.CheckBox6.Checked):3,' CheckBox6');
  writeln(aaa,IfTrue(Form3.CheckBox7.Checked):3,' CheckBox7');
  writeln(aaa,IfTrue(Form3.CheckBox8.Checked):3,' CheckBox8');
  {****************************************************************************}
  { Form1 }
  writeln(aaa,'Form1');
  writeln(aaa,IfTrue(Form1.CheckBox1.Checked):3,' CheckBox1');
  writeln(aaa,IfTrue(Form1.CheckBox2.Checked):3,' CheckBox2');
  writeln(aaa,IfTrue(Form1.CheckBox3.Checked):3,' CheckBox3');
  writeln(aaa,IfTrue(Form1.CheckBox4.Checked):3,' CheckBox4');
  writeln(aaa,IfTrue(Form1.CheckBox5.Checked):3,' CheckBox5');
  writeln(aaa,IfTrue(Form1.CheckBox6.Checked):3,' CheckBox6');
  writeln(aaa,IfTrue(Form1.Smpl1.Checked):3,'                       Smpl1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl2.Checked):3,'                       Smpl2: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl3.Checked):3,'                       Smpl3: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl4.Checked):3,'                       Smpl4: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl5.Checked):3,'                       Smpl5: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl6.Checked):3,'                       Smpl6: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl7.Checked):3,'                       Smpl7: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl8.Checked):3,'                       Smpl8: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl9.Checked):3,'                       Smpl9: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl0.Checked):3,'                       Smpl0: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl10.Checked):3,'                      Smpl10: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl11.Checked):3,'                      Smpl11: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl12.Checked):3,'                      Smpl12: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl13.Checked):3,'                      Smpl13: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl14.Checked):3,'                      Smpl14: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl15.Checked):3,'                      Smpl15: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl16.Checked):3,'                      Smpl16: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl17.Checked):3,'                      Smpl17: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl18.Checked):3,'                      Smpl18: TMenuItem');
  writeln(aaa,IfTrue(Form1.Smpl19.Checked):3,'                      Smpl19: TMenuItem');
  writeln(aaa,IfTrue(Form1.File1.Checked):3,'                       File1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Parameters1.Checked):3,'                 Parameters1: TMenuItem');
  writeln(aaa,IfTrue(Form1.HHtype2.Checked):3,'                     HHtype2: TMenuItem');
  writeln(aaa,IfTrue(Form1.Passive1.Checked):3,'                    Passive1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Calmar1.Checked):3,'                     Calmar1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Destexhe1.Checked):3,'                   Destexhe1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Migliore1.Checked):3,'                   Migliore1: TMenuItem');
  writeln(aaa,IfTrue(Form1.HHorder1.Checked):3,'                    HHorder1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N1point1.Checked):3,'                    N1point1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N2points1.Checked):3,'                   N2points1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Chow1.Checked):3,'                       Chow1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Lyle1.Checked):3,'                       Lyle1: TMenuItem');
  writeln(aaa,IfTrue(Form1.TVDscheme1.Checked):3,'                  TVDscheme1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Thread1.Checked):3,'                     Thread1: TMenuItem');
  writeln(aaa,IfTrue(Form1.NotNoisySteadyRate1.Checked):3,'         NotNoisySteadyRate1: TMenuItem');
  writeln(aaa,IfTrue(Form1.NoisySteadyRate1.Checked):3,'            NoisySteadyRate1: TMenuItem');
  writeln(aaa,IfTrue(Form1.SteadyStateOfPopModel1.Checked):3,'      SteadyStateOfPopModel1: TMenuItem');
  writeln(aaa,IfTrue(Form1.HHtype11.Checked):3,'                    HHtype11: TMenuItem');
  writeln(aaa,IfTrue(Form1.Chow2.Checked):3,'                       Chow2: TMenuItem');
  writeln(aaa,IfTrue(Form1.Calmar2.Checked):3,'                     Calmar2: TMenuItem');
  writeln(aaa,IfTrue(Form1.Passive2.Checked):3,'                    Passive2: TMenuItem');
  writeln(aaa,IfTrue(Form1.HHorder11.Checked):3,'                   HHorder11: TMenuItem');
  writeln(aaa,IfTrue(Form1.N2points2.Checked):3,'                   N2points2: TMenuItem');
  writeln(aaa,IfTrue(Form1.N1point2.Checked):3,'                    N1point2: TMenuItem');
  writeln(aaa,IfTrue(Form1.View1.Checked):3,'                       View1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Phasespace1.Checked):3,'                 Phasespace1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Inspector1.Checked):3,'                  Inspector1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Putwindowsattopleft1.Checked):3,'        Putwindowsattopleft1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Run1.Checked):3,'                        Run1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N0d1.Checked):3,'                        N0d1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Simplex1.Checked):3,'                    Simplex1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N2D1.Checked):3,'                        N2D1: TMenuItem');
  writeln(aaa,IfTrue(Form1.V1Ring1.Checked):3,'                     V1Ring1: TMenuItem');
  writeln(aaa,IfTrue(Form1.RebuildAColumn1.Checked):3,'             RebuildAColumn1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Pause1.Checked):3,'                      Pause1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Stop1.Checked):3,'                       Stop1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Clear1.Checked):3,'                      Clear1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N1.Checked):3,'                          N1: TMenuItem');
  writeln(aaa,IfTrue(Form1.fIcurve1.Checked):3,'                    fIcurve1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Rose1.Checked):3,'                       Rose1: TMenuItem');
  writeln(aaa,IfTrue(Form1.ArtificialSlice1.Checked):3,'            ArtificialSlice1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Thomsoncat1.Checked):3,'                 Thomsoncat1: TMenuItem');
  writeln(aaa,IfTrue(Form1.V1ringtest5.Checked):3,'                 V1ringtest5: TMenuItem');
  writeln(aaa,IfTrue(Form1.V1ringtest55.Checked):3,'                V1ringtest55: TMenuItem');
  writeln(aaa,IfTrue(Form1.V1ringtest6.Checked):3,'                 V1ringtest6: TMenuItem');
  writeln(aaa,IfTrue(Form1.GJ_Sotn.Checked):3,'                     GJ_Sotn: TMenuItem');
  writeln(aaa,IfTrue(Form1.N2.Checked):3,'                          N2: TMenuItem');
  writeln(aaa,IfTrue(Form1.N3.Checked):3,'                          N3: TMenuItem');
  writeln(aaa,IfTrue(Form1.ArtificialSlice.Checked):3,'             ArtificialSlice: TMenuItem');
  writeln(aaa,IfTrue(Form1.FullForm11.Checked):3,'                  FullForm11: TMenuItem');
  writeln(aaa,IfTrue(Form1.N4.Checked):3,'                          N4: TMenuItem');
  writeln(aaa,IfTrue(Form1.N5.Checked):3,'                          N5: TMenuItem');
  writeln(aaa,IfTrue(Form1.N6.Checked):3,'                          N6: TMenuItem');
  writeln(aaa,IfTrue(Form1.V1ringtest5PSP.Checked):3,'              V1ringtest5PSP: TMenuItem');
  writeln(aaa,IfTrue(Form1.FittoPSCsPSPs.Checked):3,'               FittoPSCsPSPs: TMenuItem');
  writeln(aaa,IfTrue(Form1.Help1.Checked):3,'                       Help1: TMenuItem');
  writeln(aaa,IfTrue(Form1.LIF1.Checked):3,'                        LIF1: TMenuItem');
  writeln(aaa,IfTrue(Form1.PouillePSCPSP1.Checked):3,'              PouillePSCPSP1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N7.Checked):3,'                          N7: TMenuItem');
  writeln(aaa,IfTrue(Form1.Savesettingstofile1.Checked):3,'         Savesettingstofile1: TMenuItem');
  writeln(aaa,IfTrue(Form1.Loadsettingsfromfile1.Checked):3,'       Loadsettingsfromfile1: TMenuItem');
  {****************************************************************************}
  writeln(aaa,'Empty');
  {****************************************************************************}
  { Form24 }
  writeln(aaa,'Form3');
  for ib:=1 to NofPWmax do write(aaa,BlankedPW[ib,1]:3,' ');  writeln(aaa);
  for ib:=1 to NofPWmax do write(aaa,BlankedPW[ib,2]:3,' ');  writeln(aaa);
  writeln(aaa,IfTrue(Form24.CheckBox1.Checked):3,' CheckBox1');
  writeln(aaa,IfTrue(Form24.CheckBox2.Checked):3,' CheckBox2');
  writeln(aaa,Form24.ComboBox1.ItemIndex:3,' ComboBox1');
  {**********}
  writeln(aaa,IfTrue(Form4.CheckBox21.Checked):3,' Form4.CheckBox21');
  writeln(aaa,Form4.DDSpinEdit77.Value:9:4,' :Form4.DDSpinEdit77');
  writeln(aaa,Form4.DDSpinEdit78.Value:9:4,' :Form4.DDSpinEdit78');
  writeln(aaa,IfTrue(Form4.CheckBox13.Checked):3,' Form4.CheckBox13');
  writeln(aaa,Form25.DDSpinEdit79.Value:9:4,' :Form25.DDSpinEdit79');
  writeln(aaa,'Empty');
  writeln(aaa,'Empty');
  writeln(aaa,'Empty');
  writeln(aaa,IfTrue(Form1.LFP1.Checked):3,' :Form1.LFP1: TMenuItem');
  writeln(aaa,'Empty');
  writeln(aaa,IfTrue(Form1.Bazhenov1.Checked):3,'  :Form1.Bazhenov1: TMenuItem');
  writeln(aaa,IfTrue(Form1.N2pMainenSejn1.Checked):3,'  :Form1.N2pMainenSejn1: TMenuItem');
  writeln(aaa,Form4.DDSpinEdit79.Value:9:4,' :Form4.DDSpinEdit79');
  writeln(aaa,Form4.DDSpinEdit82.Value:9:4,' :Form4.DDSpinEdit82');
  writeln(aaa,IfTrue(Form4.CheckBox7.Checked):3,' Form4.CheckBox7');
  writeln(aaa,Form4.RadioGroup1.ItemIndex:3,' Form4.RadioGroup1');
  writeln(aaa,IfTrue(Form1.N2pActiveDend1.Checked):3,'  :Form1.N2pActiveDend1: TMenuItem');
  writeln(aaa,Form3.DDSpinEdit22.Value:9:4,' :Form3.DDSpinEdit22');
  writeln(aaa,IfTrue(Form3.Visible):3,' Form3.Visible');
  writeln(aaa,IfTrue(LGN_Form1.Visible):3,' LGN_Form1.Visible');
  writeln(aaa,IfTrue(LGN_Form15.Visible):3,' LGN_Form15.Visible');
  writeln(aaa,Form15.Frame15.ComboBox1.ItemIndex:3,' Form15.Frame15.ComboBox1');
  { Form26 }
  writeln(aaa,'Form26');
  writeln(aaa,Form26.DDSpinEdit1.Value:9:4,' :Form26.DDSpinEdit1');
  writeln(aaa,Form26.DDSpinEdit2.Value:9:4,' :Form26.DDSpinEdit2');
  writeln(aaa,Form26.DDSpinEdit3.Value:9:4,' :Form26.DDSpinEdit3');
  writeln(aaa,Form26.DDSpinEdit4.Value:9:4,' :Form26.DDSpinEdit4');
  writeln(aaa,Form26.DDSpinEdit5.Value:9:4,' :Form26.DDSpinEdit5');
  writeln(aaa,Form26.DDSpinEdit6.Value:9:4,' :Form26.DDSpinEdit6');
  writeln(aaa,Form26.DDSpinEdit7.Value:9:4,' :Form26.DDSpinEdit7');
  writeln(aaa,Form26.DDSpinEdit8.Value:9:4,' :Form26.DDSpinEdit8');
  writeln(aaa,Form26.DDSpinEdit9.Value:9:4,' :Form26.DDSpinEdit9');
  writeln(aaa,Form26.DDSpinEdit10.Value:9:4,' :Form26.DDSpinEdit10');
  writeln(aaa,Form26.DDSpinEdit11.Value:9:4,' :Form26.DDSpinEdit11');
  writeln(aaa,Form26.DDSpinEdit12.Value:9:4,' :Form26.DDSpinEdit12');
  writeln(aaa,Form26.DDSpinEdit13.Value:9:4,' :Form26.DDSpinEdit13');
  writeln(aaa,Form26.DDSpinEdit14.Value:9:4,' :Form26.DDSpinEdit14');
  writeln(aaa,Form26.DDSpinEdit15.Value:9:4,' :Form26.DDSpinEdit15');
  writeln(aaa,Form26.DDSpinEdit16.Value:9:4,' :Form26.DDSpinEdit16');
  writeln(aaa,IfTrue(Form26.CheckBox1.Checked):3,' :Form26.CheckBox1');
  writeln(aaa,IfTrue(Form26.CheckBox2.Checked):3,' :Form26.CheckBox2');
  writeln(aaa,IfTrue(Form26.CheckBox3.Checked):3,' :Form26.CheckBox3');
  writeln(aaa,IfTrue(Form26.CheckBox4.Checked):3,' :Form26.CheckBox4');
  writeln(aaa,Form26.RadioGroup1.ItemIndex:3,' :Form26.RadioGroup1.ItemIndex');
  writeln(aaa,IfTrue(Form4.CheckBox17.Checked):3,' Form4.CheckBox17');
  writeln(aaa,Form4.DDSpinEdit95.Value:9:4,' :DDSpinEdit95');
  writeln(aaa,Form4.DDSpinEdit99.Value:9:4,' :DDSpinEdit99');
  writeln(aaa,Form4.i3_Combo.ItemIndex:3,' :Form4.i3_Combo.ItemIndex');
  writeln(aaa,Form26.DDSpinEdit17.Value:9:4,' :Form26.DDSpinEdit17');
  writeln(aaa,Form26.DDSpinEdit18.Value:9:4,' :Form26.DDSpinEdit18');
  writeln(aaa,Form26.DDSpinEdit19.Value:9:4,' :Form26.DDSpinEdit19');
  writeln(aaa,Form26.DDSpinEdit20.Value:9:4,' :Form26.DDSpinEdit20');
  writeln(aaa,Form26.DDSpinEdit21.Value:9:4,' :Form26.DDSpinEdit21');
  writeln(aaa,Form26.RadioGroup2.ItemIndex:3,' :Form26.RadioGroup2.ItemIndex');
  writeln(aaa,Form3.DDSpinEdit23.Value:9:4,' :Form3.DDSpinEdit23');
  writeln(aaa,Form3.DDSpinEdit28.Value:9:4,' :Form3.DDSpinEdit28');
  writeln(aaa,Form25.RadioGroup1.ItemIndex:3,' :Form25.RadioGroup1.ItemIndex');
  writeln(aaa,Form3.DDSpinEdit29.Value:9:4,' :Form3.DDSpinEdit29');
  writeln(aaa,IfTrue(Form3.CheckBox10.Checked):3,' Form3.CheckBox10');
  writeln(aaa,Form3.DDSpinEdit30.Value:9:4,' :Form3.DDSpinEdit30');
  writeln(aaa,Form3.ComboBox4.ItemIndex:3,' Form3.ComboBox4');
  writeln(aaa,Form3.ComboBox5.ItemIndex:3,' Form3.ComboBox5');
  writeln(aaa,Form4.DDSpinEdit100.Value:9:4,' :Form4.DDSpinEdit100');
  writeln(aaa,Form4.ComboBox8.ItemIndex:3,' Form4.ComboBox8');
  writeln(aaa,Form4.ComboBox9.ItemIndex:3,' Form4.ComboBox9');
  writeln(aaa,Form4.Memo1.Lines[0]);
  writeln(aaa,Form4.DDSpinEdit101.Value:9:4,' :Form4.DDSpinEdit101');
  writeln(aaa,IfTrue(Form3.CheckBox11.Checked):3,' Form3.CheckBox11');
  writeln(aaa,Form15.DDSpinEdit3.Value:9:4,' :Form15.DDSpinEdit3');
  writeln(aaa,Form15.DDSpinEdit4.Value:9:4,' :Form15.DDSpinEdit4');
  writeln(aaa,IfTrue(Form3.CheckBox12.Checked):3,' Form3.CheckBox12');
  writeln(aaa,Form30.DDSpinEdit1.Value:9:4,' :Form30.DDSpinEdit1');
  writeln(aaa,Form30.DDSpinEdit2.Value:9:4,' :Form30.DDSpinEdit2');
  writeln(aaa,Form30.DDSpinEdit3.Value:9:4,' :Form30.DDSpinEdit3');
  writeln(aaa,Form30.DDSpinEdit4.Value:9:4,' :Form30.DDSpinEdit4');
  writeln(aaa,Form30.DDSpinEdit5.Value:9:4,' :Form30.DDSpinEdit5');
  writeln(aaa,Form30.DDSpinEdit6.Value:9:4,' :Form30.DDSpinEdit6');
  writeln(aaa,Form30.DDSpinEdit7.Value:9:4,' :Form30.DDSpinEdit7');
  writeln(aaa,Form30.DDSpinEdit8.Value:9:4,' :Form30.DDSpinEdit8');
  writeln(aaa,Form30.DDSpinEdit9.Value:9:4,' :Form30.DDSpinEdit9');
  writeln(aaa,Form30.DDSpinEdit10.Value:9:4,' :Form30.DDSpinEdit10');
  writeln(aaa,Form30.DDSpinEdit11.Value:9:4,' :Form30.DDSpinEdit11');
  writeln(aaa,Form30.DDSpinEdit12.Value:9:4,' :Form30.DDSpinEdit12');
  writeln(aaa,Form30.DDSpinEdit13.Value:9:4,' :Form30.DDSpinEdit13');
  writeln(aaa,Form30.DDSpinEdit14.Value:9:4,' :Form30.DDSpinEdit14');
  writeln(aaa,Form30.DDSpinEdit15.Value:9:4,' :Form30.DDSpinEdit15');
  writeln(aaa,Form30.DDSpinEdit16.Value:9:4,' :Form30.DDSpinEdit16');
  writeln(aaa,IfTrue(Form11.Visible):3,' Form11.Visible');
  writeln(aaa,IfTrue(Form30.Visible):3,' Form30.Visible');
  writeln(aaa,IfTrue(Form31.Visible):3,' Form31.Visible');
  writeln(aaa,Form26.DDSpinEdit22.Value:9:4,' :Form26.DDSpinEdit22');
  writeln(aaa,Form26.DDSpinEdit23.Value:9:4,' :Form26.DDSpinEdit23');
  writeln(aaa,IfTrue(Form4.CheckBox22.Checked):3,' :Form4.CheckBox22');
  writeln(aaa,IfTrue(Form25.CheckBox1.Checked):3,' :Form25.CheckBox1');
  writeln(aaa,IfTrue(Form31.CheckBox1.Checked):3,' :Form31.CheckBox1');
  writeln(aaa,IfTrue(Form31.CheckBox2.Checked):3,' :Form31.CheckBox2');
  writeln(aaa,IfTrue(Form31.CheckBox3.Checked):3,' :Form31.CheckBox3');
  { Synaptic depression }
  writeln(aaa,'Synaptic depression');
  writeln(aaa,Form4.DDSpinEdit102.Value:9:4,' :DDSpinEdit102');
  writeln(aaa,Form4.DDSpinEdit103.Value:9:4,' :DDSpinEdit103');
  writeln(aaa,Form4.DDSpinEdit104.Value:9:4,' :DDSpinEdit104');
  writeln(aaa,Form4.DDSpinEdit105.Value:9:4,' :DDSpinEdit105');
  writeln(aaa,IfTrue(Form5.CheckBox1.Checked):3,' :Form5.CheckBox1');
  writeln(aaa,IfTrue(Form5.CheckBox2.Checked):3,' :Form5.CheckBox2');
  writeln(aaa,IfTrue(Form5.CheckBox3.Checked):3,' :Form5.CheckBox3');
  writeln(aaa,Form4.DDSpinEdit117.Value:9:4,' :DDSpinEdit117');
  writeln(aaa,Form26.DDSpinEdit24.Value:9:4,' :Form26.DDSpinEdit24');
  writeln(aaa,Form26.DDSpinEdit25.Value:9:4,' :Form26.DDSpinEdit25');
  writeln(aaa,Form4.DDSpinEdit118.Value:9:4,' :DDSpinEdit118');
  writeln(aaa,Form4.DDSpinEdit119.Value:9:4,' :DDSpinEdit119');
  writeln(aaa,Form3.DDSpinEdit31.Value:9:4,' :Form3.DDSpinEdit31');
  writeln(aaa,IfTrue(Form4.CheckBox23.Checked):3,' :CheckBox23');
  writeln(aaa,Form4.Left:3,' :Form4.Left');
  writeln(aaa,Form4.Top:3,' :Form4.Top');
  writeln(aaa,Form26.DDSpinEdit26.Value:9:4,' :Form26.DDSpinEdit26');
  writeln(aaa,Form26.DDSpinEdit27.Value:9:4,' :Form26.DDSpinEdit27');
  writeln(aaa,IfTrue(Form1.CheckBox8.Checked):3,' :Form1.CheckBox8.Checked');
  writeln(aaa,Form26.RadioGroup3.ItemIndex:3,' :Form26.RadioGroup3.ItemIndex');
  writeln(aaa,Form4.DDSpinEdit72.Value:9:4,' :Form4.DDSpinEdit72');
  writeln(aaa,Form26.DDSpinEdit28.Value:9:4,' :Form26.DDSpinEdit28');
  writeln(aaa,Form26.RadioGroup4.ItemIndex:3,' :Form26.RadioGroup4.ItemIndex');
  writeln(aaa,Form26.DDSpinEdit29.Value:9:4,' :Form26.DDSpinEdit29');
  writeln(aaa,IfTrue(Form1.Experimentalnuus1.Checked):3,' Form1.Experimentalnuus1: TMenuItem');
  writeln(aaa,IfTrue(Form4.CheckBox24.Checked):3,' :Form4.CheckBox24');
  writeln(aaa,Form4.DDSpinEdit120.Value:9:4,' :Form4.DDSpinEdit120');
  writeln(aaa,IfTrue(Form4.CheckBox25.Checked):3,' :Form4.CheckBox25');
  writeln(aaa,Form3.ComboBox6.ItemIndex:3,' Form3.ComboBox6.ItemIndex');
  writeln(aaa,IfTrue(Form3.CheckBox13.Checked):3,' :Form3.CheckBox13');
  {**********}
  close(aaa);
end;

procedure LoadSettings(FName :string);
var aaa :text;
    d :double;
    i,k,ib :integer;
    s :string;
begin
  if FileExists(FName)=false then exit;
  assign(aaa,FName); reset(aaa);
  {****************************************************************************}
  { Form4 }
  readln(aaa);
  readln(aaa,d);  Form4.DDSpinEdit1.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit2.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit3.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit4.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit5.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit6.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit7.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit8.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit9.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit10.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit11.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit12.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit13.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit14.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit15.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit16.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit17.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit18.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit19.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit20.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit21.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit22.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit23.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit24.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit25.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit26.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit27.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit28.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit29.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit30.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit31.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit32.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit33.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit34.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit35.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit36.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit37.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit38.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit39.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit40.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit41.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit42.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit43.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit44.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit45.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit46.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit47.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit48.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit49.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit50.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit51.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit52.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit53.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit54.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit55.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit56.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit57.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit58.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit59.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit60.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit61.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit62.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit63.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit64.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit65.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit66.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit67.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit68.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit69.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit70.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit71.Value:=d;
  readln(aaa);  //Form4.DDSpinEdit72.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit73.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit74.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit75.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit76.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit80.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit81.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit83.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit84.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit85.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit86.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit87.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit88.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit89.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit90.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit91.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit92.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit93.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit94.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit96.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit97.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit98.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit106.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit107.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit108.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit109.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit110.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit111.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit112.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit113.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit114.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit115.Value:=d;
  readln(aaa,d);  Form4.DDSpinEdit116.Value:=d;
  { Form4.gsynC1 }
  for k:=1 to MaxNSyn do begin
      readln(aaa,d);
      Form4.gsynC1.DDSpinEditA[k].Value:=d;
  end;
  readln(aaa,i);  Form4.ComboBox1.ItemIndex:=i;
  readln(aaa,i);  Form4.ComboBox2.ItemIndex:=i;
  readln(aaa,i);  Form4.ComboBox3.ItemIndex:=i;
  readln(aaa,i);  Form4.ComboBox4.ItemIndex:=i;
  readln(aaa,i);  Form4.ComboBox5.ItemIndex:=i;
  readln(aaa,i);  Form4.ComboBox6.ItemIndex:=i;
  readln(aaa,i);  Form4.CheckBox1.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox2.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox3.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox4.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox5.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox6.Checked:=(i=1);
  readln(aaa);  
  readln(aaa,i);  Form4.CheckBox8.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox9.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox10.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox11.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox12.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox14.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox15.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox16.Checked:=(i=1);
  readln(aaa,i);  Form4.ComboBox7.ItemIndex:=i;
  readln(aaa,i);  Form4.CheckBox18.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox19.Checked:=(i=1);
  readln(aaa,i);  Form4.CheckBox20.Checked:=(i=1);
  {****************************************************************************}
  { Form3 }
  readln(aaa);
  readln(aaa,d);  Form3.DDSpinEdit1.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit2.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit3.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit4.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit5.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit6.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit7.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit8.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit9.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit10.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit11.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit12.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit13.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit14.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit15.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit16.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit17.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit18.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit19.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit20.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit21.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit24.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit25.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit26.Value:=d;
  readln(aaa,d);  Form3.DDSpinEdit27.Value:=d;
  readln(aaa,i);  Form3.ComboBox1.ItemIndex:=i;
  readln(aaa,i);  Form3.ComboBox2.ItemIndex:=i;
  readln(aaa,i);  Form3.ComboBox3.ItemIndex:=i;
  readln(aaa,i);  Form3.CheckBox1.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox2.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox3.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox4.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox5.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox6.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox7.Checked:=(i=1);
  readln(aaa,i);  Form3.CheckBox8.Checked:=(i=1);
  {****************************************************************************}
  { Form1 }
  if not(eof(aaa)) then begin readln(aaa);                                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox1.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox2.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox3.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox4.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox5.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox6.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl2.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl3.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl4.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl5.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl6.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl7.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl8.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl9.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl0.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl10.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl11.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl12.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl13.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl14.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl15.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl16.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl17.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl18.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Smpl19.Checked:=(i=1);      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.File1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Parameters1.Checked:=(i=1); end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.HHtype2.Checked:=(i=1);     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Passive1.Checked:=(i=1);    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Calmar1.Checked:=(i=1);     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Destexhe1.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Migliore1.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.HHorder1.Checked:=(i=1);    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N1point1.Checked:=(i=1);    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N2points1.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Chow1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Lyle1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.TVDscheme1.Checked:=(i=1);  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Thread1.Checked:=(i=1);     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.NotNoisySteadyRate1.Checked:=(i=1);    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.NoisySteadyRate1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.SteadyStateOfPopModel1.Checked:=(i=1); end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.HHtype11.Checked:=(i=1);               end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Chow2.Checked:=(i=1);                  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Calmar2.Checked:=(i=1);                end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Passive2.Checked:=(i=1);               end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.HHorder11.Checked:=(i=1);              end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N2points2.Checked:=(i=1);              end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N1point2.Checked:=(i=1);               end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.View1.Checked:=(i=1);                  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Phasespace1.Checked:=(i=1);            end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Inspector1.Checked:=(i=1);             end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Putwindowsattopleft1.Checked:=(i=1);   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Run1.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N0d1.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Simplex1.Checked:=(i=1);               end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N2D1.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.V1Ring1.Checked:=(i=1);                end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.RebuildAColumn1.Checked:=(i=1);        end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Pause1.Checked:=(i=1);                 end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Stop1.Checked:=(i=1);                  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Clear1.Checked:=(i=1);                 end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N1.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.fIcurve1.Checked:=(i=1);               end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Rose1.Checked:=(i=1);                  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.ArtificialSlice1.Checked:=(i=1);       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Thomsoncat1.Checked:=(i=1);            end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.V1ringtest5.Checked:=(i=1);            end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.V1ringtest55.Checked:=(i=1);           end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.V1ringtest6.Checked:=(i=1);            end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.GJ_Sotn.Checked:=(i=1);                end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N2.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N3.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.ArtificialSlice.Checked:=(i=1);        end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.FullForm11.Checked:=(i=1);             end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N4.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N5.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N6.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.V1ringtest5PSP.Checked:=(i=1);         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.FittoPSCsPSPs.Checked:=(i=1);          end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Help1.Checked:=(i=1);                  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.LIF1.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.PouillePSCPSP1.Checked:=(i=1);         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.N7.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Savesettingstofile1.Checked:=(i=1);    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Loadsettingsfromfile1.Checked:=(i=1);  end;
  {****************************************************************************}
  if not(eof(aaa)) then begin readln(aaa);    {Empty}                             end;
  {****************************************************************************}
  { Form24 }
  if not(eof(aaa)) then begin readln(aaa);                                                 end;
  if not(eof(aaa)) then begin  for ib:=1 to NofPWmax do read(aaa,BlankedPW[ib,1]); readln(aaa);  end;
  if not(eof(aaa)) then begin  for ib:=1 to NofPWmax do read(aaa,BlankedPW[ib,2]); readln(aaa);  end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form24.CheckBox1.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form24.CheckBox2.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form24.ComboBox1.ItemIndex:=i;                     end;
  {**********}
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox21.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit77.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit78.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox13.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form25.DDSpinEdit79.Value:=d;                      end;
  if not(eof(aaa)) then begin readln(aaa);    {Empty}                                      end;
  if not(eof(aaa)) then begin readln(aaa);    {Empty}                                      end;
  if not(eof(aaa)) then begin readln(aaa);    {Empty}                                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.LFP1.Checked:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa);    {Empty}                                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  if (Form1.Bazhenov1.Checked     =false)and(i=1) then begin Form1.Bazhenov1.Checked     :=true; Change_HH_type(1);   end; end;
  if not(eof(aaa)) then begin readln(aaa,i);  if (Form1.N2pMainenSejn1.Checked=false)and(i=1) then begin Form1.N2pMainenSejn1.Checked:=true; Change_HH_order(1);  end; end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit79.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit82.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox7.Checked:=(i=1);                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.RadioGroup1.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  if (Form1.N2pActiveDend1.Checked=false)and(i=1) then begin Form1.N2pActiveDend1.Checked:=true; Change_HH_order(1);  end; end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit22.Value:=d;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.Visible:=(i=1);                              end;
  if not(eof(aaa)) then begin readln(aaa,i);  LGN_Form1.Visible:=(i=1);                          end;
  if not(eof(aaa)) then begin readln(aaa,i);  LGN_Form15.Visible:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form15.Frame15.ComboBox1.ItemIndex:=i;             end;
  { Form26 }
  if not(eof(aaa)) then begin readln(aaa);                                                 end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit1.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit2.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit3.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit4.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit5.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit6.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit7.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit8.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit9.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit10.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit11.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit12.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit13.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit14.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit15.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit16.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.CheckBox1.Checked:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.CheckBox2.Checked:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.CheckBox3.Checked:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.CheckBox4.Checked:=(i=1);                         end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.RadioGroup1.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox17.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit95.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit99.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.i3_Combo.ItemIndex:=i;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit17.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit18.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit19.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit20.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit21.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.RadioGroup2.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit23.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit28.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form25.RadioGroup1.ItemIndex:=i;             end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit29.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.CheckBox10.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit30.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.ComboBox4.ItemIndex:=i;                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.ComboBox5.ItemIndex:=i;                      end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit100.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.ComboBox8.ItemIndex:=i;                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.ComboBox9.ItemIndex:=i;                      end;
  if not(eof(aaa)) then begin readln(aaa,s);  Form4.Memo1.Lines[0]:=s;                           end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit101.Value:=d;                      end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.CheckBox11.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form15.DDSpinEdit3.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form15.DDSpinEdit4.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.CheckBox12.Checked:=(i=1);                   end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit1.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit2.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit3.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit4.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit5.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit6.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit7.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit8.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit9.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit10.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit11.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit12.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit13.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit14.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit15.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form30.DDSpinEdit16.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form11.Visible:=(i=1);                              end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form30.Visible:=(i=1);                              end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form31.Visible:=(i=1);                              end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit22.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit23.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox22.Checked:=(i=1);                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form25.CheckBox1.Checked:=(i=1);                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form31.CheckBox1.Checked:=(i=1);                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form31.CheckBox2.Checked:=(i=1);                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form31.CheckBox3.Checked:=(i=1);                    end;
  { Synaptic depression }
  if not(eof(aaa)) then begin readln(aaa);                                                 end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit102.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit103.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit104.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit105.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form5.CheckBox1.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form5.CheckBox2.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form5.CheckBox3.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit117.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit24.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit25.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit118.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit119.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form3.DDSpinEdit31.Value:=d;                        end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox23.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.Left:=i;                    end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.Top:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit26.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit27.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.CheckBox8.Checked:=(i=1);                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.RadioGroup3.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit72.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit28.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form26.RadioGroup4.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form26.DDSpinEdit29.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form1.Experimentalnuus1.Checked:=(i=1); end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox24.Checked:=(i=1); end;
  if not(eof(aaa)) then begin readln(aaa,d);  Form4.DDSpinEdit120.Value:=d;                       end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form4.CheckBox25.Checked:=(i=1); end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.ComboBox6.ItemIndex:=i;                     end;
  if not(eof(aaa)) then begin readln(aaa,i);  Form3.CheckBox13.Checked:=(i=1); end;
                        end;
  {**********}
  close(aaa);
  TakeParametersFromForms;
  Application.ProcessMessages;
  CorrespondParametersToTheForm;
end;

end.
